name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
      env:
        # For a project page set to "/<repo>/". For a user/org site set to "/".
        BASE_HREF: /${{ github.event.repository.name }}/
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Build (production)
        run: npm run build -- --configuration production --base-href ${{ env.BASE_HREF }}

      - name: Add SPA fallback
        run: |
          cp dist/maplestory-classic-web/browser/index.html dist/maplestory-classic-web/browser/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The Angular build outputs the production-ready files in the `browser` subfolder.
          publish_dir: ./dist/maplestory-classic-web/browser